services:
  supervisor:
    tty: true # Makes log level colors visible
    build: .
    container_name: rust_supervisor_docker
    ports:
      - "3005:8080"
    privileged: true
    env_file: .env
    volumes:
      - ./instance/configs:/app/instance/configs
      - ./instance/modules:/app/instance/modules
      - ./instance/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.16.0.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    # deploy:
    #   resources:
    #     limits:
    #       memory: 250M

networks:
  default:
    external: true
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
